Public Class UserForm

    Private Sub Guna2Button1_Click(sender As Object, e As EventArgs) Handles Guna2Button1.Click
        If Guna2TextBox1.Text = "3DDD-GT98-WM1L-4GJL" Then
            MsgBox("Welcome", MsgBoxStyle.Information, Title:="Blockman Mods")
            My.Settings.password = "correct_password"
            My.Settings.Save()
            
            Main.Show()
            Me.Hide()
        Else
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            MsgBox("Wrong password !", MsgBoxStyle.Critical, Title:="Blockman Mods")
            Return
        End If
    End Sub
End Class
